name: Publish Results to GitHub Pages

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [main]  # Or your default branch

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Run your script
        run: |
          python your_script.py  # Make sure it writes to results/

      - name: Upload to GitHub Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: results/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
